const LANGUAGES=[
  {code:'en',name:'English',    cc:'gb', note:'',           extra:[]},
  {code:'no',name:'Norwegian',  cc:'no', note:'Norsk',      extra:['Å','Ø','Æ']},
  {code:'es',name:'Spanish',    cc:'es', note:'Español',  extra:['Ñ']},
  {code:'fr',name:'French',     cc:'fr', note:'Français', extra:['É','È','Ê','À','Ù','Î','Ô','Ç','Œ']},
  {code:'de',name:'German',     cc:'de', note:'Deutsch',    extra:['Ä','Ö','Ü','ß']},
  {code:'it',name:'Italian',    cc:'it', note:'Italiano',   extra:['À','È','É','Ì','Ò','Ù']},
  {code:'pt',name:'Portuguese', cc:'pt', note:'Português',extra:['Ã','Á','Â','Ç','Ê','Ó','Ô','Õ','Ú']},
  {code:'nl',name:'Dutch',      cc:'nl', note:'Nederlands', extra:['Ë','Ï','Ó','Ú']},
  {code:'sv',name:'Swedish',    cc:'se', note:'Svenska',    extra:['Å','Ä','Ö']},
  {code:'da',name:'Danish',     cc:'dk', note:'Dansk',      extra:['Å','Ø','Æ']},
  {code:'fi',name:'Finnish',    cc:'fi', note:'Suomi',      extra:['Ä','Ö']},
  {code:'pl',name:'Polish',     cc:'pl', note:'Polski',     extra:['Ą','Ć','Ę','Ł','Ń','Ó','Ś','Ź','Ż']},
  {code:'ro',name:'Romanian',   cc:'ro', note:'Română',extra:['Ă','Â','Î','Ș','Ț']},
  {code:'tr',name:'Turkish',    cc:'tr', note:'Türkçe',extra:['Ç','Ğ','İ','Ö','Ş','Ü']},
  {code:'id',name:'Indonesian', cc:'id', note:'Bahasa',     extra:[]},
];
